name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: tty-pt/ci/.github/workflows/all-in-one.yml@main
    with:
      name: 7ways
      publish_to: "deb,apk,rpm,brew,openbsd,winget"
      deps: "libgeo,libqgl"
      deps_openbsd: "libqsys,libgeo,libqgl"
      deps_winget: "mingw-w64-x86_64-glfw,mingw-w64-x86_64-libpng,mingw-w64-x86_64-glew,mingw-w64-x86_64-xxhash"
      deps_winget_tty: "libqsys,libqmap,libgeo,libqgl"
    secrets:
      HOST: ${{ secrets.OPENBSD_HOST }}
      USER: ${{ secrets.OPENBSD_USER }}
      SSH_KEY: ${{ secrets.OPENBSD_SSH_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.OPENBSD_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.OPENBSD_GPG_PASSPHRASE }}
      GPG_KEYID: ${{ secrets.OPENBSD_GPG_KEY_ID }}
      ABUILD_PRIVATE_KEY: ${{ secrets.ABUILD_PRIVATE_KEY }}
      ABUILD_PUBLIC_KEY: ${{ secrets.ABUILD_PUBLIC_KEY }}
      TAP_TOKEN: ${{ secrets.TAP_TOKEN }}
